version: '3.8'

services:
  # web:
  #   container_name: web
  #   restart: always
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - app
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    container_name: streamlit_app
    volumes:
      - './frontend:/app'

